name = "mi-mailing"
main = "src/index.js"
compatibility_date = "2026-03-01"
workers_dev = true

[vars]
RESEND_FROM = "Mainline Intelligence <no-reply@pixelplaceofficial.com>"
NEWSLETTER_PDF_URL = "https://pyx-ai.web.app/mainlineintelligence/newsletters/mi-newsletter-002.pdf"

[[kv_namespaces]]
binding = "SUBSCRIBERS"
id = "a6192a2952c743af84fa69155cbd8522"
